### get one user
GET http://localhost:3000/api/v1/users/64b008500aec2f387391b673


### register user
POST http://localhost:3000/api/v1/auth/signup HTTP/1.1
Content-Type: application/json

{
  "username":"nivethan",
  "email":"gmail",
  "password":"123"
}

### login user
POST http://localhost:3000/api/v1/auth/signin HTTP/1.1
Content-Type: application/json

{
  "username":"nivethan",
  "password":"123"
}


### Create a new blog post
POST http://localhost:3000/api/v1/blogs HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGIwMDg1MDBhZWMyZjM4NzM5MWI2NzMiLCJpYXQiOjE2ODkzOTUyMTYsImV4cCI6MTY4OTQzODQxNn0.mtcRxxGuqs-WPdUOrNSpVJKMr4oHJslRLiyJRv92kXQ

{
  "heading": "Blog post about recroot",
  "body": "recroot",
  "author": "614c57f9a4c7c729a0552a5d"
}

### Get all blog posts
GET http://localhost:3000/api/v1/blogs HTTP/1.1

### Get a specific blog post
GET http://localhost:3000/api/v1/blogs/64b0bdd1ac95496a525de14e HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGIwMDg1MDBhZWMyZjM4NzM5MWI2NzMiLCJpYXQiOjE2ODkzMTQ4OTYsImV4cCI6MTY4OTM1ODA5Nn0.vqIp_o7G7ZPda0UjFPLcEhCChrfrQR1C-SKRepoyBW8

### Update a blog post
PUT http://localhost:3000/api/v1/blogs/64b0bdd1ac95496a525de14e HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGIwMDg1MDBhZWMyZjM4NzM5MWI2NzMiLCJpYXQiOjE2ODkzMTQ4OTYsImV4cCI6MTY4OTM1ODA5Nn0.vqIp_o7G7ZPda0UjFPLcEhCChrfrQR1C-SKRepoyBW8

{
  "heading": "Updated Blog Post",
  "body": "This is the updated content of the blog post."
}


### Delete a blog post
DELETE http://localhost:3000/api/v1/blogs/64b0c296ac95496a525de157 HTTP/1.1
